=begin
#Error Tracking REST API

#This schema describes the API endpoints for the error tracking feature

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.0

=end

# Common files
require 'error_tracking_open_api/api_client'
require 'error_tracking_open_api/api_error'
require 'error_tracking_open_api/version'
require 'error_tracking_open_api/configuration'
