# frozen_string_literal: true

require "rubocop"
require_relative "../lib/rustocop/artifact_store"
require_relative "../lib/rustocop/compatibility_status"
require_relative "../lib/rustocop/repository_layout"

LAYOUT = Rustocop::RepositoryLayout.default
ROOT = LAYOUT.root
SUPPORT_OUTPUT = LAYOUT.path("docs", "cop-support.md")
REMAINING_OUTPUT = LAYOUT.path("docs", "remaining-cops.md")
UNIT_MANIFEST = LAYOUT.path("spec", "fixtures", "unit_manifest.json")

report_path = File.expand_path(
  ARGV.fetch(0) { abort "Usage: ruby script/generate_project_parity_docs.rb FULL_AUDIT.json" }
)
abort "project parity report not found: #{report_path}" unless File.file?(report_path)

begin
  report = Rustocop::ArtifactStore.read_json(report_path, label: "project audit report")
rescue Rustocop::ArtifactStore::Error => e
  abort e.message
end
all_results = report.fetch("combined_by_cop")
registry = Rustocop::CompatibilityStatus.load(root: ROOT).built_in_cops.sort
missing = registry - all_results.keys
unless missing.empty?
  abort "report is missing active RuboCop #{RuboCop::Version::STRING} cops: #{missing.join(', ')}"
end
results = all_results.slice(*registry)

unit_manifest = JSON.parse(File.read(UNIT_MANIFEST))
passing_fixture_cops = unit_manifest.fetch("cops").filter_map do |cop, entry|
  project_derived = File.foreach(LAYOUT.path("spec", "fixtures", entry.fetch("cases"))).any? do |line|
    JSON.parse(line).fetch("origins", []).any? { |origin| origin["kind"] == "legacy_project" }
  end
  [cop, true] if project_derived
end.to_h
pending_rows = []
pending_fixture_cops = {}
fixture_evidence = lambda do |cop|
  passing = passing_fixture_cops[cop]
  pending = pending_fixture_cops[cop]
  next "Project-derived + pending" if passing && pending
  next "Project-derived" if passing
  next "Pending unit" if pending

  "No"
end
classification_labels = {
  "project_exact" => "Project-exact",
  "dormant" => "Dormant",
  "mismatch" => "Mismatch",
  "crash" => "Rust crash",
  "rubocop_error" => "RuboCop gate error"
}.freeze
counts = results.values.map { |entry| entry.fetch("classification") }.tally
rust_source = if report["rust_commit"]
                "commit #{report.fetch("rust_commit")}"
              elsif report["cop_source_sha256"]
                "cop source #{report.fetch("cop_source_sha256")}"
              else
                "native #{report.fetch("native_sha256")}"
              end

summary_rows = classification_labels.filter_map do |classification, label|
  count = counts.fetch(classification, 0)
  "| #{label} | #{count} |" unless count.zero?
end
cop_rows = registry.map do |cop|
  result = results.fetch(cop)
  values = %w[rustocop rubocop exact].map { |key| result[key].nil? ? "—" : result.fetch(key) }
  "| `#{cop}` | #{classification_labels.fetch(result.fetch("classification"))} | " \
    "#{values.join(" | ")} | #{fixture_evidence.call(cop)} |"
end

source = report_path.delete_prefix("#{ROOT}/")
support = <<~MARKDOWN
  # Built-in cop evidence

  Generated by `ruby script/generate_project_parity_docs.rb #{source}` from the
  active-cop slice of the complete #{report.fetch("projects").length}-project audit of RuboCop #{report.fetch("rubocop_version")}.
  Evidence updated at `#{report.fetch("generated_at")}`.

  This is an evidence table, not a promise of full RuboCop compatibility.
  **Project-exact** means complete diagnostic signatures matched for this one
  pinned configuration and corpus. **Dormant** means neither engine exercised
  the cop. A regression fixture records a previously observed edge case, but one
  fixture cannot establish general compatibility. Autocorrection and
  configuration branches require their own differential fixtures.

  - Rust source: `#{rust_source}`
  - Native SHA-256: `#{report.fetch("native_sha256")}`
  - Active cops: #{registry.length}
  - Intentionally pending cops: #{Rustocop::CompatibilityStatus.load(root: ROOT).intentionally_pending_cops.length}
  - Pinned projects: #{report.fetch("projects").length}
  - Cops with project-derived unit contracts: #{passing_fixture_cops.length}
  - Pending isolated mismatch directions: #{pending_rows.length}

  | Classification | Cops |
  | --- | ---: |
  #{summary_rows.join("\n")}

  ## Complete matrix

  | Cop | Project status | Rustocop | RuboCop | Exact | Project-derived unit evidence |
  | --- | --- | ---: | ---: | ---: | --- |
  #{cop_rows.join("\n")}
MARKDOWN
Rustocop::ArtifactStore.atomic_write(SUPPORT_OUTPUT, support)

unresolved = results.filter_map do |cop, result|
  classification = result.fetch("classification")
  next if %w[project_exact dormant].include?(classification)

  rust = result["rustocop"]
  ruby = result["rubocop"]
  exact = result["exact"]
  gap = if rust && ruby && exact
          (rust - exact) + (ruby - exact)
        end
  [cop, classification, rust, ruby, exact, gap]
end
unresolved.sort_by! { |cop, _classification, _rust, _ruby, _exact, gap| [-(gap || -1), cop] }
remaining_rows = unresolved.map do |cop, classification, rust, ruby, exact, gap|
  values = [rust, ruby, exact, gap].map { |value| value.nil? ? "—" : value }
  "| `#{cop}` | #{classification_labels.fetch(classification)} | #{values.join(" | ")} | " \
    "#{fixture_evidence.call(cop)} |"
end

remaining = <<~MARKDOWN
  # Current project-parity gaps

  Generated from the same complete audit as [the evidence matrix](cop-support.md).
  Evidence updated at `#{report.fetch("generated_at")}`.
  This queue contains only failures from that #{report.fetch("projects").length}-project audit; it does not use the old
  Verified/Heuristic qualification labels or captured-case pass counts.

  The gap is unmatched complete diagnostic signatures, not the difference
  between aggregate offense counts. A cop can have equal counts and still have a
  nonzero gap because its message, severity, path, or source range differs.

  - Rust source: `#{rust_source}`
  - Unresolved cops: #{unresolved.length}

  | Cop | Status | Rustocop | RuboCop | Exact | Signature gap | Project regression evidence |
  | --- | --- | ---: | ---: | ---: | ---: | --- |
  #{remaining_rows.join("\n")}
MARKDOWN
remaining.sub!(/\n+\z/, "\n")
Rustocop::ArtifactStore.atomic_write(REMAINING_OUTPUT, remaining)

puts "wrote docs/cop-support.md and docs/remaining-cops.md from #{source}"
