# frozen_string_literal: true

require "json"
require "rubocop"

ROOT = File.expand_path("..", __dir__)
SUPPORT_OUTPUT = File.join(ROOT, "docs", "cop-support.md")
REMAINING_OUTPUT = File.join(ROOT, "docs", "remaining-cops.md")
MANIFEST = File.join(ROOT, "spec", "fixtures", "project_parity_regressions", "manifest.tsv")

report_path = File.expand_path(
  ARGV.fetch(0) { abort "Usage: ruby script/generate_project_parity_docs.rb FULL_AUDIT.json" }
)
abort "project parity report not found: #{report_path}" unless File.file?(report_path)

report = JSON.parse(File.read(report_path))
results = report.fetch("combined_by_cop")
registry = RuboCop::Cop::Registry.global.map(&:cop_name).sort
unless results.keys.sort == registry
  abort "report is not a complete RuboCop #{RuboCop::Version::STRING} registry audit"
end

fixture_cops = File.readlines(MANIFEST, chomp: true).drop(1).to_h do |line|
  [line.split("\t", 2).first, true]
end
classification_labels = {
  "project_exact" => "Project-exact",
  "dormant" => "Dormant",
  "mismatch" => "Mismatch",
  "crash" => "Rust crash",
  "rubocop_error" => "RuboCop gate error"
}.freeze
counts = results.values.map { |entry| entry.fetch("classification") }.tally

summary_rows = classification_labels.filter_map do |classification, label|
  count = counts.fetch(classification, 0)
  "| #{label} | #{count} |" unless count.zero?
end
cop_rows = registry.map do |cop|
  result = results.fetch(cop)
  values = %w[rustocop rubocop exact].map { |key| result[key].nil? ? "—" : result.fetch(key) }
  "| `#{cop}` | #{classification_labels.fetch(result.fetch("classification"))} | " \
    "#{values.join(" | ")} | #{fixture_cops[cop] ? "Yes" : "No"} |"
end

source = report_path.delete_prefix("#{ROOT}/")
support = <<~MARKDOWN
  # Built-in cop evidence

  Generated by `ruby script/generate_project_parity_docs.rb #{source}` from the
  complete ten-project audit of RuboCop #{report.fetch("rubocop_version")}.

  This is an evidence table, not a promise of full RuboCop compatibility.
  **Project-exact** means complete diagnostic signatures matched for this one
  pinned configuration and corpus. **Dormant** means neither engine exercised
  the cop. A regression fixture records a previously observed edge case, but one
  fixture cannot establish general compatibility. Autocorrection and
  configuration branches require their own differential fixtures.

  - Rust source: `#{report.fetch("rust_commit")}`
  - Native SHA-256: `#{report.fetch("native_sha256")}`
  - Pinned projects: #{report.fetch("projects").length}
  - Minimized project regressions: #{fixture_cops.length}

  | Classification | Cops |
  | --- | ---: |
  #{summary_rows.join("\n")}

  ## Complete matrix

  | Cop | Project status | Rustocop | RuboCop | Exact | Regression fixture |
  | --- | --- | ---: | ---: | ---: | --- |
  #{cop_rows.join("\n")}
MARKDOWN
File.write(SUPPORT_OUTPUT, support)

unresolved = results.filter_map do |cop, result|
  classification = result.fetch("classification")
  next if %w[project_exact dormant].include?(classification)

  rust = result["rustocop"]
  ruby = result["rubocop"]
  exact = result["exact"]
  gap = if rust && ruby && exact
          (rust - exact) + (ruby - exact)
        end
  [cop, classification, rust, ruby, exact, gap]
end
unresolved.sort_by! { |cop, _classification, _rust, _ruby, _exact, gap| [-(gap || -1), cop] }
remaining_rows = unresolved.map do |cop, classification, rust, ruby, exact, gap|
  values = [rust, ruby, exact, gap].map { |value| value.nil? ? "—" : value }
  "| `#{cop}` | #{classification_labels.fetch(classification)} | #{values.join(" | ")} | " \
    "#{fixture_cops[cop] ? "Yes" : "No"} |"
end

remaining = <<~MARKDOWN
  # Current project-parity gaps

  Generated from the same complete audit as [the evidence matrix](cop-support.md).
  This queue contains only current ten-project failures; it does not use the old
  Verified/Heuristic qualification labels or captured-case pass counts.

  The gap is unmatched complete diagnostic signatures, not the difference
  between aggregate offense counts. A cop can have equal counts and still have a
  nonzero gap because its message, severity, path, or source range differs.

  - Rust source: `#{report.fetch("rust_commit")}`
  - Unresolved cops: #{unresolved.length}

  | Cop | Status | Rustocop | RuboCop | Exact | Signature gap | Regression fixture |
  | --- | --- | ---: | ---: | ---: | ---: | --- |
  #{remaining_rows.join("\n")}
MARKDOWN
File.write(REMAINING_OUTPUT, remaining)

puts "wrote docs/cop-support.md and docs/remaining-cops.md from #{source}"
