# frozen_string_literal: true

require "fileutils"
require "rubocop"
require_relative "../lib/rustocop/compatibility_status"

ROOT = File.expand_path("..", __dir__)
OUTPUT = File.join(ROOT, "docs", "cop-support.md")

native = ENV.fetch("RUSTOCOP_NATIVE_PATH", File.join(ROOT, "libexec", "rustocop-native"))
raise "native Rustocop executable not found at #{native}" unless File.executable?(native)

supported_cops = IO.popen([native, "--show-cops"], &:readlines).map(&:strip).reject(&:empty?)
compatibility_status = Rustocop::CompatibilityStatus.load(root: ROOT)
upstream_status = compatibility_status.data
verified_cops = compatibility_status.verified_cops
hardened_cops = compatibility_status.hardened_cops

registry = RuboCop::Cop::Registry.global.to_a.sort_by(&:cop_name)
names = registry.map(&:cop_name)
heuristic_cops = (supported_cops & names) - verified_cops
missing_cops = names - verified_cops - heuristic_cops

status = lambda do |cop_name|
  if verified_cops.include?(cop_name)
    "Verified"
  elsif heuristic_cops.include?(cop_name)
    "Heuristic"
  else
    "Missing"
  end
end

departments = registry.group_by(&:department).sort.to_h
department_rows = departments.map do |department, cops|
  counts = cops.map { |cop| status.call(cop.cop_name) }.tally
  hardened = cops.count { |cop| hardened_cops.include?(cop.cop_name) }
  "| #{department} | #{cops.length} | #{counts.fetch("Verified", 0)} | #{hardened} | " \
    "#{counts.fetch("Heuristic", 0)} | #{counts.fetch("Missing", 0)} |"
end

cop_rows = registry.map do |cop|
  autocorrect = cop.support_autocorrect? ? "Yes" : "No"
  "| `#{cop.cop_name}` | #{status.call(cop.cop_name)} | #{autocorrect} |"
end

hardening_rows = compatibility_status.hardening_entries.map do |cop, evidence|
  "| `#{cop}` | #{evidence.fetch("categories").map { |category| "`#{category}`" }.join(", ")} | " \
    "#{evidence.fetch("evidence").map { |path| "`#{path}`" }.join("<br>")} |"
end

document = <<~MARKDOWN
  # Built-in RuboCop cop support

  Generated by `bundle exec ruby script/generate_cop_support.rb` against RuboCop #{RuboCop::Version::STRING}.

  “Verified” means Rustocop passes every executable upstream diagnostic case for that cop and every correction assertion in those cases. “Hardened” is an additional evidence level: the cop also passes the required adversarial categories recorded in `spec/hardening/status.yml`. “Heuristic” means a native implementation exists but does not yet pass the complete upstream cop spec. “Missing” means Rustocop has no native implementation.

  ## Summary

  - Built-in cops: #{registry.length}
  - Verified: #{verified_cops.count { |cop| names.include?(cop) }}
  - Hardened: #{hardened_cops.count { |cop| names.include?(cop) }}
  - Heuristic: #{heuristic_cops.length}
  - Missing: #{missing_cops.length}
  - Upstream RuboCop suite: #{upstream_status.dig("upstream_rspec", "examples")} examples, #{upstream_status.dig("upstream_rspec", "failures")} failures, #{upstream_status.dig("upstream_rspec", "pending")} upstream pendings
  - Captured compatibility cases: #{upstream_status.fetch("captured_cases")} across all #{upstream_status.dig("diagnostic_baseline", "total_cops")} cops
  - Current diagnostic baseline: #{upstream_status.dig("diagnostic_baseline", "passed_cases")}/#{upstream_status.fetch("captured_cases")} cases; correction assertions are also green for every cop marked Verified

  | Department | Built-in | Verified | Hardened | Heuristic | Missing |
  | --- | ---: | ---: | ---: | ---: | ---: |
  #{department_rows.join("\n")}

  ## Hardened evidence

  | Cop | Adversarial categories | Evidence |
  | --- | --- | --- |
  #{hardening_rows.join("\n")}

  ## Complete matrix

  | Cop | Status | RuboCop autocorrect |
  | --- | --- | --- |
  #{cop_rows.join("\n")}
MARKDOWN

FileUtils.mkdir_p(File.dirname(OUTPUT))
File.write(OUTPUT, document)

puts "wrote #{OUTPUT}: #{verified_cops.length} verified, #{hardened_cops.length} hardened, " \
  "#{heuristic_cops.length} heuristic, #{missing_cops.length} missing"
