# frozen_string_literal: true

require "optparse"
require "pathname"
require "set"
require "tempfile"
require "yaml"

module Rustocop
  class ConfigurationCompiler
    SCHEMA_VERSION = 1

    def self.call(argv = ARGV)
      new(argv).call
    end

    def initialize(argv)
      @argv = argv.dup
    end

    def call
      options = parse_options
      source = source_path(options.fetch(:source))
      output = output_path(source, options[:output])
      rendered = render(compile(source, output))
      return check(output, rendered) if options[:check]

      raise "refusing to overwrite #{output}; pass --force to replace it" if File.exist?(output) && !options[:force]

      write(output, rendered)
      puts output
      0
    rescue LoadError, StandardError => e
      warn "rustocop-config: #{e.message}"
      2
    end

    private

    attr_reader :argv

    def parse_options
      options = { source: ".rubocop.yml", output: nil, force: false, check: false }
      parser = OptionParser.new do |arguments|
        arguments.banner = "Usage: rustocop-config [options]"
        arguments.on("-c", "--config PATH", "source RuboCop configuration") { |value| options[:source] = value }
        arguments.on("-o", "--output PATH", "compiled Rustocop configuration") { |value| options[:output] = value }
        arguments.on("--force", "replace an existing output file") { options[:force] = true }
        arguments.on("--check", "fail when the compiled configuration is stale") { options[:check] = true }
      end
      parser.parse!(argv)
      raise OptionParser::InvalidArgument, "unexpected arguments: #{argv.join(' ')}" unless argv.empty?

      options
    end

    def source_path(value)
      path = File.expand_path(value)
      raise "could not read config #{path}" unless File.file?(path)

      path
    end

    def output_path(source, requested)
      return File.expand_path(requested) if requested

      basename = File.basename(source).sub("rubocop", "rustocop")
      File.join(File.dirname(source), basename)
    end

    def compile(source, output)
      require "rubocop"

      project_root = File.dirname(source)
      output_root = File.dirname(output)
      base_cops = RuboCop::Cop::Registry.global.names.to_set
      store = RuboCop::ConfigStore.new
      store.options_config = source
      config = store.for_dir(File.dirname(source))
      enabled = RuboCop::Cop::Registry.global.enabled(config).map(&:cop_name).to_set
      configured = config.to_h

      document = {
        "Rustocop" => {
          "SchemaVersion" => SCHEMA_VERSION,
          "SourceConfig" => relative_path(source, output_root),
          "ProjectRoot" => relative_path(project_root, output_root),
          "RuboCopVersion" => RuboCop::Version::STRING,
          "BuiltInCops" => base_cops.to_a.sort,
          "NonNativeCops" => (enabled - base_cops).to_a.sort
        },
        "AllCops" => normalize(configured.fetch("AllCops", {}), project_root)
      }
      base_cops.sort.each do |name|
        settings = normalize(configured.fetch(name, {}), project_root)
        settings["Enabled"] = enabled.include?(name)
        document[name] = settings
      end
      document
    end

    def normalize(value, project_root)
      case value
      when Hash
        value.to_h { |key, nested| [key.to_s, normalize(nested, project_root)] }
      when Array
        value.map { |nested| normalize(nested, project_root) }
      when Regexp
        value.source
      when Symbol
        value.to_s
      when String
        project_relative_path(value, project_root)
      else
        value
      end
    end

    def relative_path(path, root)
      Pathname.new(path).relative_path_from(Pathname.new(root)).to_s
    end

    def project_relative_path(value, project_root)
      prefix = "#{project_root}/"
      return "." if value == project_root

      value.start_with?(prefix) ? value.delete_prefix(prefix) : value
    end

    def render(document)
      "# Generated by rustocop-config. Regenerate this file instead of editing it.\n#{YAML.dump(document)}"
    end

    def check(output, rendered)
      if File.file?(output) && File.read(output) == rendered
        puts output
        return 0
      end

      warn "rustocop-config: #{output} is missing or stale; regenerate it with rustocop-config --force"
      1
    end

    def write(output, rendered)
      directory = File.dirname(output)
      raise "output directory does not exist: #{directory}" unless Dir.exist?(directory)

      Tempfile.create([".rustocop", ".yml"], directory) do |temporary|
        temporary.write(rendered)
        temporary.flush
        temporary.fsync
        File.rename(temporary.path, output)
      end
    end
  end
end
